name: ppfive-dev
channels:
  - conda-forge
  - nodefaults  # stay away from Anaconda like the plague

dependencies:
  - python >=3.11
  - numpy >=1.24
  - fsspec >=2024.3.0
  - pyfive >=1.1.2
  - pytest >=8
  - pytest-xdist
  - udunits2  # cf-python needs it
  - pip
  - pip:
      - cf-python @ git+https://github.com/davidhassell/cf-python.git@kerchunk-read
      - cfdm @ git+https://github.com/davidhassell/cfdm.git@pyfive-netcdf
